### ISSUE TITLE
error when try to install/update

### ISSUE THREAD

**Issue by jmanuelfuentes** [embl-cba/fiji-plugin-bigDataProcessor#5]
[ERROR] null
java.io.FileNotFoundException: http://sites.imagej.net/EMBL-CBA/jars/fiji-plugin-bigDataProcessor2-0.2.00.jar-20190311120000
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at net.imagej.updater.util.Downloader.download(Downloader.java:117)
	at net.imagej.updater.util.Downloader.start(Downloader.java:98)
	at net.imagej.updater.Installer.start(Installer.java:154)
	at net.imagej.ui.swing.updater.UpdaterFrame.install(UpdaterFrame.java:629)
	at net.imagej.ui.swing.updater.UpdaterFrame$13.run(UpdaterFrame.java:566)
Caused by: java.io.FileNotFoundException: http://sites.imagej.net/EMBL-CBA/jars/fiji-plugin-bigDataProcessor2-0.2.00.jar-20190311120000
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3000)
	at java.net.HttpURLConnection.getHeaderFieldDate(HttpURLConnection.java:552)
	at java.net.URLConnection.getLastModified(URLConnection.java:559)
	at net.imagej.updater.util.Downloader.download(Downloader.java:108)
	... 4 more

**Comment by tischi** [comment]
could you try again now?

**Comment by jmanuelfuentes** [comment]
Fixed it!
